
version: '3.8'
services:
  llm_host_service:
    image: ollama/ollama:latest
    ports:
      - "8220:11434"
    runtime: nvidia  # Specify the NVIDIA runtime for Docker to use the GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: serve
    networks:
      - doc_intellect_network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env.development
    ports:
      - "8762:5173"
    depends_on:
      - llm_interaction_service
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - doc_intellect_network

  llm_interaction_service:
    restart: unless-stopped
    hostname: llm_interaction_service
    build:
      context: ./llm_interaction_service
      dockerfile: Dockerfile
    ports:
      - "8222:8000"
    depends_on:
      - llm_host_service
      # - vector_db
      # - db
    volumes:
      - "./llm_interaction_service/app:/app/app"
    environment:
      - ENV=development
    networks:
      - doc_intellect_network

  # llm_service:
  #   build:
  #     context: ./data_processing_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8000"
  #   depends_on:
  #     - vector_db
  #     - db

  # chat_service:
  #   build:
  #     context: ./chat_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8003:8000"
  #   depends_on:
  #     - db

  # auth_service:
  #   build:
  #     context: ./auth_service
  #     dockerfile: Dockerfile
  #     ports:
  #       - "8006:8000"
  #     depends_on:
  #       - db

  # dashboard_service:
  #   build:
  #     context: ./dashboard_service
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8007:8000"
  #   depends_on:
  #     - db

  # vector_db:
  #   image: chromadb/chroma:latest
  #   ports:
  #     - "8004:8004"
  #   volumes:
  #     - vector_data:/data

#   db:
#     image: postgres:17-bookworm
#     environment:
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: chat_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   vector_data:
#   db_data:

networks:
  doc_intellect_network:
    driver: bridge
